### ISSUE TITLE
TypeError: doSnipe() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by bkang97** [earshel/PokeyPySnipe#14]
When inputting data into the localhost webpage, the page returns an internal server error and the console returns: "TypeError: doSnipe() takes exactly 3 arguments (2 given)"

**Comment by earshel** [comment]
I just committed a new snipe.py - please try that and report back. Thanks :+1: !

**Comment by bkang97** [comment]
worked thanks!!
