### ISSUE TITLE
Doesn't work if you only have regular Pokeballs

### ISSUE THREAD

**Issue by stumpyb** [earshel/PokeyPySnipe#16]
This works great when I have Greatballs but if I only have Pokeballs it crashes with this error:

> Line 113,snipe.py - 2016-08-02 09:56:14,551 - INFO - Found a MAGIKARP, 68.126522 meters away 
> 
> Line 133,snipe.py - 2016-08-02 09:56:14,551 - INFO - MAGIKARP appears to be the rarest Pokemon @ location. Let's catch him!
> Line 301,snipe.py - 2016-08-02 09:56:15,160 - INFO - Encountered pokemon - moving back to start location to catch.
> Line 303,snipe.py - 2016-08-02 09:56:15,160 - INFO - Ignore CP: True
> Line 172,snipe.py - 2016-08-02 09:56:17,162 - CRITICAL - [1, 2, 3]
> Line 181,snipe.py - 2016-08-02 09:56:17,162 - INFO - We have 11 Poke Balls
> [2016-08-02 09:56:17,163] ERROR in app: Exception on /_snipe_ [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "snipe.py", line 46, in remote_Snipe
>     doSnipe(session,config,snipecoords,pokemonName)
>   File "snipe.py", line 317, in doSnipe
>     snipe = snipeABitch(session, pokeMon, remoteEncounter)
>   File "snipe.py", line 211, in snipeABitch
>     elif bestball != items.UNKNOWN:
> NameError: global name 'bestball' is not defined
> Line 1587,app.py - 2016-08-02 09:56:17,163 - ERROR - Exception on /_snipe_ [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "snipe.py", line 46, in remote_Snipe
>     doSnipe(session,config,snipecoords,pokemonName)
>   File "snipe.py", line 317, in doSnipe
>     snipe = snipeABitch(session, pokeMon, remoteEncounter)
>   File "snipe.py", line 211, in snipeABitch
>     elif bestball != items.UNKNOWN:
> NameError: global name 'bestball' is not defined

Great work on this by the way!

**Comment by earshel** [comment]
Thanks, Stumpyb - I just committed a new snipe.py that should resolve this. Mind testing it out and reporting back? I don't have an account with only Poke Balls in it. Cheers!

**Comment by stumpyb** [comment]
Your commit fixed it, thanks!

**Comment by earshel** [comment]
Glad to hear it - thanks for pointing out the issue. Happy sniping ;)
