### ISSUE TITLE
How use

### ISSUE THREAD

**Issue by ghost** [earshel/PokeyPySnipe#17]
You have missing files...

**Comment by earshel** [comment]
MrCarlosJr - I just downloaded this repo and installed it on a machine that's never seen Python and it works fine. Were you receiving a specific error?

**Comment by ghost** [comment]
I use in linux... have one tutorial?

**Comment by earshel** [comment]
Unfortunately, I don't have a Linux distro to test this on at the moment, but it should be cross-platform. Just follow the instructions and run snipe.py. I'll test it on Linux when I get home from work this afternoon.

**Comment by rirze** [comment]
@MrCarlosJr Make a `snipe.sh` file in the `pogo` directory with the following content:

```
python snipe.py -a"Choose google or ptc" -u"Your Username" -p"Your Password" -l"Enter Location Here" 
```

Then run this script and open the url in your browser to start sniping.

**Comment by earshel** [comment]
@rirze This is incorrect as of the latest commit. Rather than the arguments being read in fro mthe bat or sh file, they are now read from config.ini :).

**Comment by rirze** [comment]
@earshel Ah, sorry, I haven't pulled this project in a couple days. Is the correct usage to then fill out config.ini with the right info and then run `python snipe.py`?

**Comment by earshel** [comment]
@rirze Yes, that's correct. I've made some pretty important changes in the past few commits, so it's worth re-pulling the current repo :+1:

**Comment by ghost** [comment]
git clone ....
cd ....
sudo pip install -r requirements.txt
[carlos@fedora24 PokeyPySnipe] $ sh compile.sh
compile.sh: line 4: cd: ./proto/: No such file or directory
compile.sh: line 5: ./compile.py: No such file or directory

**Comment by Pimentoso** [comment]
I use OSX but it should be the same as any linux distro. I also use virtualenv to install the python requirements locally.

```
git clone ...
cd PokeyPySnipe/
virtualenv .
source bin/activate
pip install -r requirements.txt

cd pogo/
nano config.ini
(edit the config.ini file and save)
python snipe.py
```

Then use your browser to open 0.0.0.0:5100 and snipe away. Keep the terminal open to check what's happening.
