### ISSUE TITLE
not using berry this version

### ISSUE THREAD

**Issue by alawing** [earshel/PokeyPySnipe#18]
not using berry this version

**Comment by earshel** [comment]
Fixed this issue. It now uses 1 razzberry per encounter. It's been so long that I've played legitimately that I"m not sure whether it should use one per encounter or one before each ball throw. If it's the latter please let me know and I'll fix it.

**Comment by earshel** [comment]
Also, due to the changes, it's necessary to download the entire repo again, as multiple files have changed. There's a new line in the config called useBerryThreshold, you should alter that to your preference.

**Comment by alawing** [comment]
It should one berry per ball throw. curveball + 0.1 chance, and also berry + 0.1 chance.
So my suggection is we could set the thresholdP less to save berry.
My suggestion is:
redball<blueball<blueball + berry < ultraball < ultraball + berry
