### ISSUE TITLE
Start Loc in config.ini

### ISSUE THREAD

**Issue by akocmark** [earshel/PokeyPySnipe#20]
Hi, what should I put in the start loc in the config.ini file? can I put my dubai coordinates?
Thanks

**Comment by akocmark** [comment]
and also how do I start the script?

**Comment by earshel** [comment]
@akocmark Start loc can be coordinates, must be in format: ###.#####,###.##### . In order to start the script, just run Launch.bat or snipe.py.

**Comment by akocmark** [comment]
snipe.py causes an error regarding with encrypt.dll on mac os x
i've posted the logs on the other issue. thanks

**Comment by earshel** [comment]
@akocmark Check out Kris' comment, it tells you how to get your own libencrypt.so on osx ;)
