### ISSUE TITLE
Step by step using this snipe

### ISSUE THREAD

**Issue by eengg** [earshel/PokeyPySnipe#22]
sory for creating issue.
I already succes instalation until "After install, copy requirements.txt to c:\python27\scripts, open command prompt and type pip install -r requirements.txt"

Then I Run launch.bat, its do nothing, please teach me how to using this snipe step by step.
Thx

**Comment by earshel** [comment]
@eengg no problem

Please open a command prompt and run launch.bat from there and let me know which error you receive. Did you receive any errors while installing requirements.txt?

**Comment by kriswong** [comment]
@eengg when you run pip do this command
"pip install --upgrade -r requirements.txt" 
Also ensure you have Visual C++ 9.00 which is posted in the instructions.

**Comment by Lolwa18** [comment]
hi i am getting this error
error: [Errno 10053] An established connection was aborted by the software in your host machine
any idea why?
