### ISSUE TITLE
Feature Request [Enhancement]

### ISSUE THREAD

**Issue by kriswong** [earshel/PokeyPySnipe#23]
Wondering if you are planning on implementing additional features?

Some features I'd love to see are:

**User support Features:**
- <del>Multiple Account sniping, (1 set of coordinates all account snipe target)</del> **Probably will not be able to implement this, it's beyond the scope of what I know in Python -earshel

**Pokemon Management**
- <del> Mass Evolve (Feature added to Pokemon Inventory Manager)</del> **Done -earshel
- Upgrade Pokemon feature (select a single Pokemon and it would upgrade it next lvl using stardust and candies)
- <del> Sort Pokemon (based on, IV, CP, POkedex number, etc.)</del>**Done -earshel
- <del>Select based on Criteria (CP <X, IV<X, etc) </del> **Done -earshel
- <del>Candy count area (would be nice to know what candies we have)</del> **Done -earshel

**Item Management**
Another tab that I can look at the items in the trainers inventory and discard them as wanted.

Anyways, I know you are probably busy and all but wanted to just highlight some enhancement taht would be great to see. I'm not a great developer but totally willing to help if you would like.

**Comment by rirze** [comment]
This sounds like a bot. I'm pretty sure there are more developed projects for the points under Pokemon Management and Item Management, but hey if you want to make another, go for it. I'll help out if you guys need it.

**Comment by earshel** [comment]
@kriswong  I just made a pretty large commit with new css styling on the web interface as well as implemented a sorting function. It is recommended that you re-download the entire repository since there are quite a lot of files committed. Will work on some of the other things you mentioned as well ;).

**Comment by earshel** [comment]
@kriswong I just committed again. Added evolve selected Pokemon and a candy display to each Pokemon.

**Comment by kriswong** [comment]
@earshel looks phenomenal! Thanks. I'm liking the new design too! Great job.

**Comment by earshel** [comment]
@kriswong Thanks bud! I just made a new commit for a few files (snipe.py, /templates inventory.html,dashboard.html,snipe.html,result.html, and added a few files to /avatars). Adds a little functionality and a platform for even more stuff. I recommend downloading the repo again as a whole ;)

**Comment by earshel** [comment]
@kriswong I've implemented a lot of your suggestions, thank you for all of them! I'm going to close this issue, though I will be working on implementing more when I have the time. Feel free to make pull requests if you make something better :). Check out the new repo.
