### ISSUE TITLE
On Linux, I get the following error

### ISSUE THREAD

**Issue by devs7u** [earshel/PokeyPySnipe#25]
OSError: libencrypt-linux-x86-64.so: cannot open shared object file: No such file or directory

I understand that it means it can not find that file, but it is in the correct location and everything. 
I'd appreciate help

**Comment by earshel** [comment]
@devs7u Line 538 (new repo) should look like this, since the .so file is in the /encrypt directory 

> ```
>     'encrypt/libencrypt-linux-x86-64.so', 
> ```

**Comment by devs7u** [comment]
Thanks. that solved it.

**Comment by earshel** [comment]
No worries.
