### ISSUE TITLE
Merge with PokeTrainer

### ISSUE THREAD

**Issue by wesselvdv** [earshel/PokeyPySnipe#3]
Hi!

Awesome tool you've made! Works like a charm. :-) May I suggest that you merge your capability with this Python tool: https://github.com/j-e-k/poketrainer ?

Would be awesome if we were able to utilize the sniper function from the website while running that bot. Shouldn't be too hard, it's nearly identical and you're using the same lib.

**Comment by earshel** [comment]
I'm leaving town for 4 days to go to a family reunion. Unfortunately I won't have the time to do this. I'm not opposed to the idea, though, if somebody else wants to do it ;).
