### ISSUE TITLE
Stop disconnecting after each catch

### ISSUE THREAD

**Issue by spaeck** [earshel/PokeyPySnipe#4]
How about implementing an option to NOT disconnect after each catch. would make sniping way more effective.

**Comment by Iormangund** [comment]
Aso allowing input of access token would be great for google accounts with 2 factor etc.

**Comment by earshel** [comment]
Spaeck, if you're running snipe.bat, it doesn't disconnect after each catch. The prompt which asks 'Shall we do this again?' does not lead to the login routine being re-ran, it simply re-calls the snipe function.

**Comment by Spaeck** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6218814/17222264/b5f65a4c-54f7-11e6-8db1-b1c492937481.PNG)

**Comment by spaeck** [comment]
hmm. so what am i doing wrong?
![unbenannt](https://cloud.githubusercontent.com/assets/6218814/17222331/fc7384ae-54f7-11e6-80b6-38f75b5b4422.PNG)

**Comment by earshel** [comment]
Spaeck, I'm not sure. I just converted the project to use the web service exclusively. Please try the new commit and let me know if it loops properly for you. Thanks!

**Comment by spaeck** [comment]
It loops, but the webpage (chrome browser) empties all values after sniping.
Maybe you could "keep" username, pass, and stuff...

`D:\Users\DEV\Desktop\PokeyPySnipe-master\pogo>snipe.py -a "ptc" -u "removed" -p "removed" -l "removed removed"
Line 270,snipe.py - 2016-07-28 19:47:03,121 - INFO - None
Line 105,api.py - 2016-07-28 19:47:03,122 - INFO - Creating PTC session for removed
Line 788,connectionpool.py - 2016-07-28 19:47:03,137 - INFO - Starting new HTTPS connection (1): sso.pokemon.com
Line 64,api.py - 2016-07-28 19:47:05,463 - INFO - Coordinates: 40.8024 -73.952073 0.0
Line 788,connectionpool.py - 2016-07-28 19:47:05,469 - INFO - Starting new HTTPS connection (1): pgorelease.nianticlabs.com
Line 293,snipe.py - 2016-07-28 19:47:06,214 - INFO - Successfully logged in to Pokemon Go! Starting web server on port 5100.
Line 87,_internal.py - 2016-07-28 19:47:06,229 - INFO -  \* Running on http://0.0.0.0:5100/ (Press CTRL+C to quit)
Line 87,_internal.py - 2016-07-28 19:47:16,852 - INFO - 127.0.0.1 - - [28/Jul/2016 19:47:16] "GET / HTTP/1.1" 200 -
Line 67,snipe.py - 2016-07-28 19:47:34,467 - INFO - Finding Nearby Pokemon:
Line 74,snipe.py - 2016-07-28 19:47:34,963 - INFO - Current pos: 32.815123, -96.666276
Line 95,snipe.py - 2016-07-28 19:47:34,969 - INFO - Found a DODUO, 21.477427 meters away

Line 95,snipe.py - 2016-07-28 19:47:34,973 - INFO - Found a VENONAT, 77.591563 meters away

Line 95,snipe.py - 2016-07-28 19:47:34,976 - INFO - Found a DODUO, 21.477427 meters away

Line 95,snipe.py - 2016-07-28 19:47:34,980 - INFO - Found a VENONAT, 77.591563 meters away

Line 109,snipe.py - 2016-07-28 19:47:34,983 - INFO - DODUO appears to be the rarest Pokemon @ location. Let's catch him!
Line 234,snipe.py - 2016-07-28 19:47:37,711 - INFO - Encountered pokemon - moving back to start location to catch.
Line 163,snipe.py - 2016-07-28 19:47:39,717 - INFO - Using a POKE_BALL
Line 170,snipe.py - 2016-07-28 19:47:42,144 - CRITICAL - Congrats! We caught it!

Line 240,snipe.py - 2016-07-28 19:47:42,147 - INFO - Heres what we caught:

Line 243,snipe.py - 2016-07-28 19:47:42,446 - INFO - id: removed
pokemon_id: DODUO
cp: 54
stamina: 15
stamina_max: 15
move_1: QUICK_ATTACK_FAST
move_2: DRILL_PECK
height_m: 1.42272377014
weight_kg: 43.3107833862
individual_attack: 12
individual_defense: 1
individual_stamina: 4
cp_multiplier: 0.215732470155
pokeball: ITEM_POKE_BALL
captured_cell_id: removed
creation_time_ms: removed

Line 87,_internal.py - 2016-07-28 19:47:42,461 - INFO - 127.0.0.1 - - [28/Jul/2016 19:47:42] "GET /_snipe_?authtype=ptc&username=removed&password=removed&startingloc=removed+removed&snipecoords=32.8151226%2C-96.6662761 HTTP/1.1" 200 -
Line 67,snipe.py - 2016-07-28 19:48:06,895 - INFO - Finding Nearby Pokemon:
Line 74,snipe.py - 2016-07-28 19:48:07,207 - INFO - Current pos: 32.815123, -96.666276
Line 95,snipe.py - 2016-07-28 19:48:07,211 - INFO - Found a VENONAT, 77.591563 meters away

Line 95,snipe.py - 2016-07-28 19:48:07,214 - INFO - Found a VENONAT, 77.591563 meters away

Line 109,snipe.py - 2016-07-28 19:48:07,229 - INFO - VENONAT appears to be the rarest Pokemon @ location. Let's catch him!
Line 234,snipe.py - 2016-07-28 19:48:09,924 - INFO - Encountered pokemon - moving back to start location to catch.
Line 163,snipe.py - 2016-07-28 19:48:11,930 - INFO - Using a ULTRA_BALL
Line 170,snipe.py - 2016-07-28 19:48:14,335 - CRITICAL - Congrats! We caught it!

Line 240,snipe.py - 2016-07-28 19:48:14,338 - INFO - Heres what we caught:

Line 243,snipe.py - 2016-07-28 19:48:14,664 - INFO - id: removed
pokemon_id: VENONAT
cp: 472
stamina: 69
stamina_max: 69
move_1: CONFUSION_FAST
move_2: SIGNAL_BEAM
height_m: 1.05936837196
weight_kg: 35.1153755188
individual_attack: 12
individual_defense: 5
individual_stamina: 2
cp_multiplier: 0.566754519939
pokeball: ITEM_ULTRA_BALL
captured_cell_id: removed
creation_time_ms: removed

Line 87,_internal.py - 2016-07-28 19:48:14,680 - INFO - 127.0.0.1 - - [28/Jul/2016 19:48:14] "GET /_snipe_?authtype=ptc&username=removed&password=removed&startingloc=removed+removed&snipecoords=32.8151226%2C-96.6662761 HTTP/1.1" 200 -
Line 67,snipe.py - 2016-07-28 19:48:33,882 - INFO - Finding Nearby Pokemon:
Line 74,snipe.py - 2016-07-28 19:48:34,210 - INFO - Current pos: 40.702900, -74.005700
Line 95,snipe.py - 2016-07-28 19:48:34,214 - INFO - Found a MAGIKARP, 18.057312 meters away

Line 95,snipe.py - 2016-07-28 19:48:34,219 - INFO - Found a MAGIKARP, 34.845375 meters away

Line 95,snipe.py - 2016-07-28 19:48:34,223 - INFO - Found a POLIWAG, 78.537195 meters away

Line 95,snipe.py - 2016-07-28 19:48:34,227 - INFO - Found a MAGIKARP, 18.057312 meters away

Line 95,snipe.py - 2016-07-28 19:48:34,233 - INFO - Found a MAGIKARP, 34.845375 meters away

Line 95,snipe.py - 2016-07-28 19:48:34,237 - INFO - Found a POLIWAG, 78.537195 meters away

Line 109,snipe.py - 2016-07-28 19:48:34,242 - INFO - MAGIKARP appears to be the rarest Pokemon @ location. Let's catch him!
Line 234,snipe.py - 2016-07-28 19:48:36,950 - INFO - Encountered pokemon - moving back to start location to catch.
Line 163,snipe.py - 2016-07-28 19:48:38,957 - INFO - Using a GREAT_BALL
Line 170,snipe.py - 2016-07-28 19:48:41,342 - CRITICAL - Congrats! We caught it!

Line 240,snipe.py - 2016-07-28 19:48:41,345 - INFO - Heres what we caught:

Line 243,snipe.py - 2016-07-28 19:48:41,645 - INFO - id: removed
pokemon_id: MAGIKARP
cp: 118
stamina: 28
stamina_max: 28
move_1: SPLASH_FAST
move_2: STRUGGLE
height_m: 0.948979079723
weight_kg: 12.6522016525
individual_attack: 12
individual_defense: 8
individual_stamina: 11
cp_multiplier: 0.566754519939
pokeball: ITEM_GREAT_BALL
captured_cell_id: removed
creation_time_ms: removed

Line 87,_internal.py - 2016-07-28 19:48:41,661 - INFO - 127.0.0.1 - - [28/Jul/2016 19:48:41] "GET /_snipe_?authtype=ptc&username=removed&password=removed&startingloc=removed+removed&snipecoords=40.7029%2C-74.0057+ HTTP/1.1" 200 -`

**Comment by earshel** [comment]
I removed those GET requests - if you close the snipe tab and reopen http://localhost:5100, the only communication between the dashboard and the snipe tool will be the snipecoords. The rest of the parameters are now handled by the snipe.bat file (authtype, username,password, startingloc)

**Comment by spaeck** [comment]
Works like a charm! Thanks

**Comment by earshel** [comment]
My pleasure, thanks for the feedback!
