### ISSUE TITLE
plz help :c

### ISSUE THREAD

**Issue by KitoWH** [earshel/PokeyPySnipe#6]
i've edited the snipe.bat and added my email address, password 
snipe.py -a "google" -u "******_" -p "**_****" -l "starting loc format 123.002334 11.3838484"
- here are my password, email.
  but after 1-3 seconds it close itself and when i run webserver.bat and i try to login with my password and email it shows a new window and it close again itself after 1-3 seconds.
  Python 2.7 is installed and pip, flask, and the everything from the requirements.txt what should i do now? :/
  and what does Snipe Coords? can you pls explain it? thanks.
  http://i.imgur.com/X4mPFUR.png
  http://i.imgur.com/F72sOx2.png

**Comment by earshel** [comment]
Kito, your starting loc should not have a comma in between the lat and lng, but rather a space. I haven't had an opportunity to implement any sort of formatting, so it must be exactly as Google expects it. Ex: "123.000000 12.000000" as opposed to "123.000000,12.000000"
