### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by kriswong** [earshel/PokeyPySnipe#9]
Hey is it possible to provide instructions not on the install... but how it works?

I ran this and it does not seem to work as I thought.  Thanks

**Comment by earshel** [comment]
@kriswong I've been away from home at a family reunion. If you're still looking for instructions - here you go: edit the snipe.bat file with your information, run snipe.bat, then go to a web browser and navigate to http://localhost:5100. Paste the coords to snipe and press go. It's that simple :)
